### ISSUE TITLE
cmd: pending plots changes by 1.0 release

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1414]
> Extracted from https://github.com/iterative/dvc.org/pull/1382#issuecomment-640435301 et al.

- [x] Apply changes from iterative/dvc/pull/3963 once that is merged. - https://github.com/iterative/dvc.org/issues/1414#issuecomment-730566207
- [x] Add YAML and TSV examples to plot show? Or maybe just translate JSON example to YAML and CSV to TSV.
- [x] Per https://github.com/iterative/dvc.org/pull/1382#pullrequestreview-427733327 double check about "All plots are used" in plot show -h usage (targets arg). - https://github.com/iterative/dvc.org/issues/1414#issuecomment-730558360
- [x] modify: how to make a regular output into a plot? See https://github.com/iterative/dvc/pull/3994#pullrequestreview-429085947 - #1946
- ~~Review term "props" in plots commands once the code base is final/stable (per https://github.com/iterative/dvc.org/pull/1382#pullrequestreview-427522723)~~
- [x] term: "column index" vs "column number"? See https://github.com/iterative/dvc.org/pull/1382#discussion_r438996574 and https://github.com/iterative/dvc.org/pull/1382#pullrequestreview-427729775 - #1946
- [x] For JSON plot files we say "every object should have the same structure" but actually I'm not sure what the exact restriction is. Ask/test/check. See https://github.com/iterative/dvc.org/pull/1382#pullrequestreview-427730625
- ~~Double check how to apply all Vega spec props in plots: modify subcmd only has a limited no. of options. Why isn't it like `dvc config` BTW, where you can give any key/value pair (core repo Q)?~~ Moved to iterative/dvc/issues/4909
---

- EXTRA: Possibly change the modify example explained in https://github.com/iterative/dvc.org/pull/1382#discussion_r436435646
- EXTRA: Maybe address some of the discrepancies mentioned in this https://github.com/iterative/dvc.org/pull/1380#issuecomment-640181973
- EXTRA: Is plots diff really a diff? See discussion in https://github.com/iterative/dvc.org/pull/1382#pullrequestreview-427524008
- EXTRA: See #1800

**Comment by jorgeorpinel** [comment]
@imhardikj some answers to https://github.com/iterative/dvc.org/pull/1946#issuecomment-727563679:

> > Apply changes from iterative/dvc/pull/3963
>
> These changes are already applied

No, they're not. Several cmd ref Synopsis/usage sections and maybe some option descriptions still need the updates, I think (please double check).

> > maybe just translate JSON example to YAML and CSV to TSV
>
> But this will result in same plot

Just add an expandable section under the sample data of https://dvc.org/doc/command-reference/plots/show#example-hierarchical-data to show how it looks in other formats. (Changing the extensions in some other unrelated sections doesn't sound like a useful alternative BTW.)

> > Per https://github.com/iterative/dvc.org/pull/1382#pullrequestreview-427733327
>
> I checked this with examples which has 2 and 3 plot files, plots show generated image with 2 and 3 plots respectively.

Sounds good. Can you share the example dvc.yaml file with 2-3 plots though? And DVC version, command, and result. Thanks

**Comment by jorgeorpinel** [comment]
@imhardikj remaining answers to https://github.com/iterative/dvc.org/pull/1946#issuecomment-727563679:

> > For JSON plot files we say "every object should have the same structure" but actually I'm not sure... Ask/test/check
>
> doesn't hold true...

OK that's great investigation from your part, with the plots example and everything. So we need to update the plots ref(s) to explain what the behavior and restrictions (if any) are. 1. Update the description of `<DVC_METRIC_Y>` to specify only the first row matters; 2. Update the text in the plots index to something like "array of consistent objects is expected: <what consistent means here>" (also not sure "expected" is the right term, feel free to rewrite the whole paragraph if needed).

Please do that update in it's own PR.

> > Double check how to apply all Vega spec props...
>
> I passed properties like this... `dvc plots modify logs.csv --width 1000`

Why did you expect arbitrary `--` flags to have an effect? The valid options for the command are listed in https://dvc.org/doc/command-reference/plots/modify#options and no others will work (did it give you an error message, BTW?).

Some of the options (from `x` to `title` correspond to Vega properties). You can learn more about Vega and how it relates to DVC plots here: https://dvc.org/doc/command-reference/plots/show#example-vega-specification-file.

The question was whether it's possible to modify any other Vega props other than the options that the `modify` command provides. I guess probably only via a custom template (see https://dvc.org/doc/command-reference/plots#plot-templates).

This topic is a bit advanced so feel free to give it a shot to understand and if you can come up with a new section or example somewhere on how to modify any Vega property that would be great but don't worry too much about it. It's not key info we need to provide (I'm removing the check box for now). Thanks

**Comment by imhardikj** [comment]
> Can you share the example dvc.yaml file with 2-3 plots though

@jorgeorpinel  I used `dvc.yaml` from [example-get-staretd](https://github.com/iterative/example-get-started/blob/master/dvc.yaml). I modified `plots` in `evaluate` stage like this:
```git
- prc.json:
        ...
- prc1.json:
        ...
- prc2.json:
        ...
```
 Edited similarly in `evaluate.py` to generate these files.. I changed `x` and `y` fields so plots are different
Command:
```dvc
$ dvc plots show
```
Result:

![plot](https://user-images.githubusercontent.com/33034902/99708092-5a7c0a80-2ac3-11eb-9966-bb186aace12d.JPG)

DVC version:
```
$ dvc version
DVC version: 1.10.0 (pip)
---------------------------------
Platform: Python 3.6.9 on Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: overlay on overlay
Workspace directory: overlay on overlay
Repo: dvc, git
```

**Comment by imhardikj** [comment]
> Apply changes from iterative/dvc/pull/3963
> > These changes are already applied
> > > No, they're not. Several cmd ref Synopsis/usage sections and maybe some option descriptions still need the updates.

I checked all changes in iterative/dvc/pull/3963 and those are already there in `metrics` and `plot` docs. I think all are covered by #1382 and #1444. One thing migth `plots diff` description as per https://github.com/iterative/dvc/pull/3963#pullrequestreview-426996969
According to review I think "Show multiple versions of plot metrics by overlaying them in a single plot." should be changed to "Show multiple versions of plot metrics by overlaying them in a single image."

**Comment by jorgeorpinel** [comment]
Thanks for the evidence! 🙏

**Comment by jorgeorpinel** [comment]
> already there in metrics and plot docs

I guess you're right. I was thrown off by the PR you mentioned first (#1382) which does not address that. But #1444 does. I'll mark the check box here for now! Thanks

> One thing migth plots diff description...

Yeah let's just double check that all other `metrics` and `plots` usage blocks correspond to the `-h` help output of the commands on the latest DVC version (1.9.1) please @imhardikj.

**Comment by jorgeorpinel** [comment]
Closed by #2075 but I forgot remove it's draft status before merging...
