### ISSUE TITLE
term: stop using Dvcfile

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1445]
since there's no longer a default stage name in `dvc run` 1.0

This update was started in https://github.com/iterative/dvc.org/pull/1420/commits/435f4103f031e03d7ca194890c4ec59c59430fd3 — needs to be continued in its own PR.

Docs where the term is mentioned:
- [x] push cmd ref. (#1591)
- [x] repro cmd ref. (#1504)
- ~~install/plugins (#1570)~~
- [x] versioning use case tutorial (#1526)
- Double check any other mentions (the one in install/plugins can stay for legacy compatibility)

**Comment by sarthakforwet** [comment]
@jorgeorpinel  in `push.md` file under the example `With dependencies`, following two problems come up - 
 
![dvc](https://user-images.githubusercontent.com/46163196/87216344-7ecd1b00-c35c-11ea-8fc0-db880027978f.PNG)
Here the `stages` has link to `run.md` which no clearly describes the pipeline stages. Was it linked to some pipeline stages before the new release? 

Secondly, the command `dvc pipeline show` is to be replaced with `dvc dag` and its output needs to be updated with the new syntax to output stages specified in `dvc.yaml` file. However I am not getting what new stages I should replace it with? Do these stages exist somewhere in the docs or should I go with a new example?

**Comment by jorgeorpinel** [comment]
Yes, the word "stage" is linked to the `dvc run` cmd ref in many places. Currently it's the best place where the concept of stages is clearly described, did you read it?

![image](https://user-images.githubusercontent.com/1477535/87231230-edb96c80-c37a-11ea-9efd-3516c11e35bd.png)

How does it relate to this issue, @sarthakforwet ? See #550. and replacing `pipeline` with `dag` is in #1255. Please comment in those issues accordingly, I'm hiding these comments from here. Thanks

**Comment by jorgeorpinel** [comment]
Or feel free to open a PR with any progress on the pipeline->dag issue and comment there so we continue the conversation and address your doubts. Thanks

**Comment by shcheklein** [comment]
Reopening since there are still Dvcfile in the docs?

**Comment by jorgeorpinel** [comment]
Where? Only one in content\docs\install\plugins.md which Ruslan recommended we keep for backward compatibility.

**Comment by shcheklein** [comment]
Yep, probably got removed in another PR or commits!

**Comment by jorgeorpinel** [comment]
Yeah sorry that PR was confusing. There was an overlapping one and I merged them in the right order 🙂
