### ISSUE TITLE
docs: List instances of stage file concepts, dvc run/checkout/repro for example review and update to 1.0

### ISSUE THREAD

**Issue by jeremydesroches** [iterative/dvc.org#1743]
From #1255 : 

> Create a list of places where the **concept of stage file(s)** and `dvc run/checkout/repro` are used...

List of places here, including initial example:

**Get Started**
- [x] [https://dvc.org/doc/start/data-pipelines](https://dvc.org/doc/start/data-pipelines)
- [x] [https://dvc.org/doc/start/experiments](https://dvc.org/doc/start/experiments)
- [x] Several cmd examples/links need updating (see **Command Reference** section below)

**User Guide**
- [x] [https://dvc.org/doc/user-guide/dvc-files-and-directories](https://dvc.org/doc/user-guide/dvc-files-and-directories)
- [x] [https://dvc.org/doc/user-guide/managing-external-data](https://dvc.org/doc/user-guide/managing-external-data)
- [x] [https://dvc.org/doc/user-guide/external-dependencies](https://dvc.org/doc/user-guide/external-dependencies)
- [x] [https://dvc.org/doc/user-guide/related-technologies](https://dvc.org/doc/user-guide/related-technologies)
- [x] [https://dvc.org/doc/user-guide/large-dataset-optimization](https://dvc.org/doc/user-guide/large-dataset-optimization)
- [x] [https://dvc.org/doc/user-guide/merge-conflicts](https://dvc.org/doc/user-guide/merge-conflicts)
- [x] [https://dvc.org/doc/user-guide/dvcignore](https://dvc.org/doc/user-guide/dvcignore)

**Use Cases**
- [x] [https://dvc.org/doc/use-cases/versioning-data-and-model-files/tutorial](https://dvc.org/doc/use-cases/versioning-data-and-model-files/tutorial)

**Install**
- [x] [https://dvc.org/doc/install/completion](https://dvc.org/doc/install/completion) - #1766

**Command Reference**
- [x] [https://dvc.org/doc/command-reference/run](https://dvc.org/doc/command-reference/run)
- [x] [https://dvc.org/doc/command-reference/repro](https://dvc.org/doc/command-reference/repro)
- [x] [https://dvc.org/doc/command-reference/remove](https://dvc.org/doc/command-reference/remove)
- [x] [https://dvc.org/doc/command-reference/freeze](https://dvc.org/doc/command-reference/freeze) - #1766
- [x] [https://dvc.org/doc/command-reference/unfreeze](https://dvc.org/doc/command-reference/unfreeze)- #1766
- [x] [https://dvc.org/doc/command-reference/update](https://dvc.org/doc/command-reference/update)
- [x] [https://dvc.org/doc/command-reference/dag](https://dvc.org/doc/command-reference/dag) - #1766
- [x] [https://dvc.org/doc/command-reference/fetch](https://dvc.org/doc/command-reference/fetch)
- [ ] ~~[https://dvc.org/doc/command-reference/import](https://dvc.org/doc/command-reference/import) - ok, get started examples/links need updating~~
- [ ] ~~[https://dvc.org/doc/command-reference/import-url](https://dvc.org/doc/command-reference/import-url) - ok, get started examples/links need updating~~
- [ ] ~~[https://dvc.org/doc/command-reference/commit](https://dvc.org/doc/command-reference/commit) - ok, get started examples need updating~~
- [x] [https://dvc.org/doc/command-reference/pull](https://dvc.org/doc/command-reference/pull)
- [x] [https://dvc.org/doc/command-reference/params](https://dvc.org/doc/command-reference/params)
- [x] [https://dvc.org/doc/command-reference/params/diff](https://dvc.org/doc/command-reference/params/diff) - run example out of date (fixed in #1908)
- [x] [https://dvc.org/doc/command-reference/push](https://dvc.org/doc/command-reference/push)
- [ ] ~~[https://dvc.org/doc/command-reference/checkout](https://dvc.org/doc/command-reference/checkout) - ok, get started examples need updating~~
- [ ] ~~[https://dvc.org/doc/command-reference/metrics](https://dvc.org/doc/command-reference/metrics) - ok, get started example/link needs updating~~
- [x] [https://dvc.org/doc/command-reference/metrics/diff](https://dvc.org/doc/command-reference/metrics/diff)
- [ ] ~~[https://dvc.org/doc/command-reference/metrics/show](https://dvc.org/doc/command-reference/metrics/show) - references stage file example from get started~~
- [x] [https://dvc.org/doc/command-reference/status](https://dvc.org/doc/command-reference/status)
- [x] [https://dvc.org/doc/command-reference/plots/show](https://dvc.org/doc/command-reference/plots/show)
- [x] [https://dvc.org/doc/command-reference/plots/modify](https://dvc.org/doc/command-reference/plots/modify)
- [x] [https://dvc.org/doc/command-reference/install](https://dvc.org/doc/command-reference/install) - #1766 
- [x] [https://dvc.org/doc/command-reference/config](https://dvc.org/doc/command-reference/config)
- [x] [https://dvc.org/doc/command-reference/diff](https://dvc.org/doc/command-reference/diff) - #1965

Second part from #1255, which may be better as second issue:

> We should review all those docs to make sure the use of dvc run/etc and YAML examples are updated to 1.0.

(Items in list above will be checked when checked/updated.)

**Comment by jeremydesroches** [comment]
@jorgeorpinel I'll list the issues as shown. Should the second part remain here or be it's own issue?

**Comment by jorgeorpinel** [comment]
Nice, thanks @jeremydesroches. Let's keep the 2nd part here for now. I edited the description above a bit.

**Comment by jorgeorpinel** [comment]
Hey @jeremydesroches I see all the check boxes are marked now, but only a few are addressed in PR #1766. Can you explain what happened? Thanks

**Comment by jeremydesroches** [comment]
Yes, I reviewed all the items in the list and marked them as follows:

- checked off items as when the examples and dvc run/etc applied 1.0 usage
- added link to PR "#1766" where I made edits following review
- checked off "ok" items but added notes where examples need other updates (out of date with current getting started, etc.)
- left unchecked where examples did not apply 1.0 usage and need updates as part of this issue

**Comment by jorgeorpinel** [comment]
Got it. Glad to see most of it is done then. Are you planning to finish this one off then? Or would you rather turn to SEO work at this point?

**Comment by jeremydesroches** [comment]
Happy to finish off the updates for the unchecked items. I think the checked items that need getting started references updated should be taken up in a new issue (or an appropriate existing one).

**Comment by jorgeorpinel** [comment]
OK. Also the 2nd part may be pending (dvc run/repro and YAML examples).

**Comment by jorgeorpinel** [comment]
@jeremydesroches do you think we can finish addressing this issue? The few checkboxes left seem pretty straight-forward.

**Comment by jeremydesroches** [comment]
> @jeremydesroches do you think we can finish addressing this issue? The few checkboxes left seem pretty straight-forward.

Yep @jorgeorpinel I'm on it. I'll work through the last unchecked items and verify/update the get started examples.

**Comment by jeremydesroches** [comment]
Hey @jorgeorpinel and @shcheklein, I'm trying to verify the unchecked items here. They all use the getting started example, and there's a new error when I run `dvc fetch` or `dvc checkout` after cloning the example repo.

`ERROR: failed to pull data from the cloud - Lockfile 'dvc.lock' is corrupted.`

I've tried starting over and checked my environment. Did something change with the latest updates to the example repo? I'll work on something else in the meantime. Thanks!

**Comment by jorgeorpinel** [comment]
> there's a new error when I run dvc fetch or dvc checkout after cloning the example repo.
> `ERROR: failed to pull data from the cloud - Lockfile 'dvc.lock' is corrupted.`

Shot. It looks like the example get started repo isn't compatible with the latest DVC version. I opened iterative/example-repos-dev/issues/17

**Comment by jorgeorpinel** [comment]
However that repo is no longer used directly in https://dvc.org/doc/start so you could just follow the steps manually @jeremydesroches, no?

BTW

> checkout - ok, get started examples need updating

That command is only used in https://dvc.org/doc/start/data-versioning and seems correct (wouldn't hurt to double check though).

**Comment by jorgeorpinel** [comment]
> looks like the example get started repo isn't compatible...

@jeremydesroches please install the latest version (1.10.1) BTW. You may need to download from https://github.com/iterative/dvc/releases/ as it seems the download button in the home page has them outdated (#1964)

**Comment by jeremydesroches** [comment]
> @jeremydesroches please install the latest version (1.10.1) BTW. 

Got it. Thanks for figuring this out for me. Brew is working now too.

**Comment by jorgeorpinel** [comment]
@jeremydesroches you can strikethrough or remove the bullets involving "get started" because that will have to be rewritten soon anyway. Is there anything else left here? Thanks

**Comment by jeremydesroches** [comment]
> Is there anything else left here?

OK @jorgeorpinel, struck out the "get started" bullets. Nope, nothing left here.

**Comment by jorgeorpinel** [comment]
Well, thanks for taking care of it!
