### ISSUE TITLE
cmd refs: Updates per 1.x

### ISSUE THREAD

**Issue by imhardikj** [iterative/dvc.org#1824]
All cmd refs that need to be updated per 1.x
Context: https://github.com/iterative/dvc.org/issues/1255#issuecomment-698134751

Mainly descriptions, or everything
- [x] `repro` - #1632
- ~~`dag` (rewrite description #1500)~~
- [x] `commit` (example for adding missing deps/outs #460/#612) #1840
- [x] `list` ~~+ #1521?~~
- [x]  `target` arg descriptions - #1574

Mainly examples
- [x] `run` examples in other docs ~~(also #1700 and #186)~~
- [x] `status` examples in all docs (including consistent indentation — may keep tabs) - #1952
- ~~pending `plots` updates #1175~~ #1414
- [x] `fetch` (examples) - #1903
- [x] `pull` (examples) - #1903
- [x] `get` (examples) - #1903
- [x] `params diff` (examples #1743) -
- [x] `version` - #1635
- [x] `root` (new example #404)

**Comment by jorgeorpinel** [comment]
@imhardikj please lmk when you've reviewed this list to make each check box more specific as we discussed, and I'll review and prioritize the list myself then. Thanks

**Comment by jorgeorpinel** [comment]
Closed by #2075.
