### ISSUE TITLE
2.0 docs

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2026]
> See release plan in iterative/dvc/issues/5367.

Finalize pending 1.x-related updates (extracted from #1255) - #2074

- [x] Review all .dvc file examples throughout docs (in YAML code blocks) — note we require YAML 1.2 (se iterative/dvc/pull/4415 and #1764) - mostly done #1608. 
- [x] ^ Also push/pull examples
- [x] Review DVC cache info everywhere, especially in the internal files/dirs guide.
- [x] `plots` refs per #1414
- [x] other refs? per #1824

> Would be nice to backport those to `v1` when done, if possible
---

- [x] "Parametrized" pipelines (dvc.yaml changes) - @jorgeorpinel + @skshetry (https://github.com/iterative/dvc/wiki/Parametrization) - #2052
- [x] New/changed Get Started - @dberenbaum + @jorgeorpinel 
  - New example project and story plan (including new pipelines and experiments)
  - Rewrite https://dvc.org/doc/start
- [x] "DVC Experiments" (sample project: https://github.com/dberenbaum/dvc-exp-mnist) - @jorgeorpinel + @pmrowla 
  - Doc run-cache? (#1289) — #2137
  - Prepare docs structure conceptually for regular (persistent) and new (transient) experiments.
  - Experiment Management guide (#816) — #2146
  - Document `dvc exp` refs — ~~#1926~~ #2199, others
  - Ideas: https://replicate.ai/docs/tutorial#experiments-and-checkpoints
- [x] Live metrics - @pared +? — #2227
  - Write README in that repo?
  - ~~Add refs to https://dvc.org/doc/api-reference~~
- `dvc stage` (https://github.com/iterative/dvc.org/issues/2134#issuecomment-771214046) — #2208

---

- [ ] Archived v1 docs - #2006 / #1167 + https://github.com/iterative/dvc/pull/5315
- [x] Update [Katacoda](https://github.com/iterative/dvc.org/issues?q=is%3Aissue+is%3Aopen+katacoda) scenarios - iterative/katacoda-scenarios/issues/20
- [x] `config/remote {} --repo` (#2064) - @efiop + @jorgeorpinel

**Comment by pared** [comment]
@jorgeorpinel we can skip API references for Dvclive, after iterative/dvc#5466 this method will be removed.

**Comment by jorgeorpinel** [comment]
Sounds good, thanks.

**Comment by jorgeorpinel** [comment]
Glad to report that most of the mayor stuff is done or has mergeable PRs! Changing priority here.

**Comment by jorgeorpinel** [comment]
The only pending item is "Archived v1 docs" so I'll prioritize those issues instead. Closing here!
