### ISSUE TITLE
studio: further enhancements

### ISSUE THREAD

**Issue by tapadipti** [iterative/dvc.org#2468]
This issue has been created for unresolved PR comments on https://github.com/iterative/dvc.org/pull/2455 This issue is intended to be closed before the public release (see also unresolved reviews/comments in that PR).

- [x] use images that are at least 1400px width

- [x] Should "compare" be reflected in the sidebar label?
_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc.org/pull/2455#discussion_r629711333_

- [ ] Can we make the first sentence into a p and insert an image of the `Trends` button? It's not easy to find by just looking at the view (I had to Ctrl+F the first time). Something like this:

![image](https://user-images.githubusercontent.com/1477535/117914676-6cd44580-b2a9-11eb-8362-5107e92a7a0e.png)

_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc.org/pull/2455#discussion_r630701705_

- [x] Be a bit more detailed in explaining each section? Similar to [/doc/studio/get-started#components-of-a-view](https://dvc-org-studio-docs-vntpxfoqdz.herokuapp.com/doc/studio/get-started#components-of-a-view)
_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc.org/pull/2455#discussion_r630718879_

- [x] The CI/CD part may need more explaining/linking (otherwise it's a bit misleading that DVC Studio can "run" experiments).
_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc.org/pull/2455#discussion_r630719000_

- [x] This should probably be moved down after or even merged with **Invite collaborators**.
_Originally posted by @jorgeorpinel in https://github.com/iterative/dvc.org/pull/2455#discussion_r630725402_

- [x] Docs on GitHub apps.
_Originally posted by @duijf in https://github.com/iterative/viewer/issues/2015#issuecomment-845704645_

- [x] Use trend chart from `example-get-started` project for consistency with the rest of the content. Currently, trend chart from the `jameson-metrics` project (or some other project, I'm not sure) is used.

- [x] Include "visual" in the intro sentence.
https://github.com/iterative/dvc.org/pull/2455#discussion_r631125207

- [x] Combine two of the steps in instructions to create a view and change 'click on connect' to 'click'.
https://github.com/iterative/dvc.org/pull/2455#discussion_r630618356

**Comment by tapadipti** [comment]
@duijf Are the following statements correct, and do they cover all that we need to tell users regarding authorization and GH apps? I'll revise the text, but want to make sure that the content is correct and complete.

> When someone tries to use Studio for the first time, they need to authorize DVC Studio and grant it access to their GH / Gitlab / Bitbucket repo.
> When someone tries to connect to any of their repos on GH and create a view, they need to first install the DVC Studio GH app. For this, Studio will provide a Configure button which they can use to perform the necessary authorization without learning how to do it themselves.

**Comment by duijf** [comment]
@tapadipti There are two flows:

 - GitLab and BitBucket: the user signs in and we use their OAuth token to perform actions. No additional setup is required after signing in.
 - GitHub: the user signs in. After signing in, they need to install the GitHub app on the repositories / organizations that they want to use with Studio.
    - The configure button will take users to [this page](https://github.com/apps/dvc-studio/installations/new) where they can choose what organizations / repos to install our app into.
    - This setup only needs to happen once per repository / organization.

About that last point: If a new Studio user:

 - Signs in with GitHub
 - They are a member of an organization on GitHub
 - The DVC Studio GH app is already installed into that organization

Then the user will be able to create views for the repos in that organization without having to also install the GitHub app.

> without learning how to do it themselves

Small note on the text: users do need to configure the GitHub app, so not sure what this is referring to.

**Comment by jorgeorpinel** [comment]
Will review #2510 ASAP. Please lmk if it's time sensitive (per release calendar, etc.)

**Comment by shcheklein** [comment]
One more comment from Discord: 

https://discord.com/channels/485586884165107732/841856466897469441/847752201425518623

> Hello, I'm having difficulties to setup access to my S3 remote
I've created an IAM user with read access on my S3 bucket, but the UI tells me "No permission to fetch remote data", do you know what's the minimal permissions set required to make Studio fully functional?

We'll need to have a section with the list of remotes and some basic instructions on how to setup them.

**Comment by tapadipti** [comment]
@jorgeorpinel The release is on the 2nd (Wednesday). So it's quite time-sensitive. Sorry about the short notice :(

**Comment by tapadipti** [comment]
> We'll need to have a section with the list of remotes and some basic instructions on how to setup them.

Ok. Will add the section.
