### ISSUE TITLE
guide: Experiment Management (phase 1)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2548]
We have some overview of Experiments in https://dvc.org/doc/user-guide/experiment-management and now a Checkpoints guide under that (which is at a very different level). We should probably

- [x] split the sections of that index into a page each (see https://github.com/iterative/dvc.org/pull/2654); and
- [x] extract technical details from https://dvc.org/doc/command-reference/exp (esp. `run`) to guides
- [ ] extract some? examples from https://dvc.org/doc/command-reference/exp to guides
- [x] review https://dvc.org/doc/user-guide/experiment-management/checkpoints for consistency
- [x] cover more checkpoints scenarios; at least #2568 (see https://github.com/iterative/dvc.org/pull/2753)
- [x]  #2367
- [x] ~~#2675~~ #2690
- [x] #2737
- [x] #2736
- ~~#2844 (my be~~ done by the 2 above)
- [x] #2592 
- \+ General points from https://github.com/iterative/dvc.org/issues/2995 ?

> Next: https://github.com/iterative/dvc.org/issues/2911

**Comment by jorgeorpinel** [comment]
What priority should this have @shcheklein @dberenbaum ?

**Comment by dberenbaum** [comment]
It might make sense to wait until after we finish the new get started sections for experiments and maybe the use case if we also do that one. At that point, we might have a better idea of what to do with these.

What do you think @jorgeorpinel?
