### ISSUE TITLE
guide: Modeling Pipelines

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2883]
> From https://github.com/iterative/dvc.org/issues/144#issuecomment-844711839

- [x] What are data pipelines, including DAG concept (extract from https://dvc.org/doc/command-reference/dag)

Structure:

> See #2857 for the original structure ideas.

- [x] [Defining Pipelines](https://dvc.org/doc/user-guide/pipelines/defining-pipelines)
  - [x] Focus on the pipelining process and ~~codification~~ link to dvc.yaml ref. for formalities
  - [x] ~~Defining stages (extract from `run` and `stage` refs.)~~
    - [ ] Dependencies and (general) parameters
    - [ ] Outputs and metrics/plots
  - [ ] Should provide some actual `dvc.yaml` example/templates to copy&paste.
  - [ ] Multiple dvc.yaml files vs. multiple pipelines (`repro --recursive`)
  - [ ] Describing formally outs, deps, stage doesn't make sense here
  - Mention `exp init`? (Link to appropriate page/section) [Maybe](https://github.com/iterative/dvc.org/issues/2883#issuecomment-1240994630)
- [ ] Pipeline reproduction
  - [ ] Extract some details from https://dvc.org/doc/command-reference/repro ?
- [ ] Experimental pipelines ([discussion](https://github.com/iterative/dvc.org/issues/2883#issuecomment-1244806361))
- [ ] Operationalizing pipelines?

Other tasks

- [ ] https://github.com/iterative/dvc.org/issues/4267
- [ ] Mention VS Code "as an editor that supports schema definition, etc."
- [ ] Update some of the [stage] links around this term that currently go to `run/stage` refs (some should link to the concept page instead)
- [ ] Recover some info deleted in [this change to Running Experiments](https://github.com/iterative/dvc.org/pull/3182/files#diff-213c105f41cfb7e3abe29cba4fd80d9cf459bb94703b0a49708b23cf6b6cf5c5) ?
- [ ] https://github.com/iterative/dvc.org/issues/3670

**Comment by jorgeorpinel** [comment]
Updated [plan](https://github.com/iterative/dvc.org/issues/2883#issue-1013656881) for this epic per https://github.com/iterative/dvc.org/pull/3414#issuecomment-1238505396. PTAL @dberenbaum @shcheklein

**Comment by dberenbaum** [comment]
Thanks @jorgeorpinel!

My specific feedback on https://github.com/iterative/dvc.org/pull/3414#issuecomment-1238505396:

> We should probably talk more about dvc exp init here? (since it helps to bootstrap the dvc.yaml after all)?

We can mention `dvc exp init`, but I think it's still immature and we are discussing how to improve this onboarding experience now, so it might end up being very short-lived.

> we should provide some example - actual pipepline files?

Yes, I think having some templates that people can copy and paste would help people get started as much as `dvc exp init`.

> mention VS Code as an editor that supports schema definition

Yes, I think we could mention VS Code as one example of an editor and show how these editors can be used to write/modify/validate dvc.yaml files.

> Include things like Jupyter notebooks - how to make a pipeline out of it ... etc

Yeah, definitely useful although probably a fairly large project on its own. I know @RCdeWit and @alex000kim are working on something related, so it would be good to sync with them.

**Comment by jorgeorpinel** [comment]
> My specific feedback on https://github.com/iterative/dvc.org/pull/3414#issuecomment-1238505396:

Cc @shcheklein

**Comment by shcheklein** [comment]
I think this item `Defining stages (extract from run and stage refs.)` doesn't make sense anymore.

> Operationalizing pipelines
> Experimental pipelines

I'm not sure what it means

> Pipeline reproduction

Running pipeline? - we can include both exp and repro I guess. No need to complicate

>  so it might end up being very short-lived.

even so, it's fine to mention, i think

**Comment by jorgeorpinel** [comment]
> having some templates that people can copy and paste

Added to description.

**Comment by jorgeorpinel** [comment]
> Defining stages (extract from run and stage refs.) doesn't make sense anymore.

Scratched out now (I left it since it's been done in the current doc).

> Experimental pipelines

Overlap between `exp` and dvc.yaml features. Overlaps with https://github.com/iterative/dvc.org/issues/2768 in that "removing the pipeline and stages concept would be ideal," (from [Running Exps](https://dvc.org/doc/user-guide/experiment-management/running-experiments)).

If it's not a lot it could be a section in **Pipeline reproduction**.

> Operationalizing pipelines

Using pipelines in production. Probably the last topic to worry about or maybe not even for docs.

**Comment by jorgeorpinel** [comment]
> Operationalizing pipelines

Maybe [CML](https://cml.dev/doc/cml-with-dvc)?
