### ISSUE TITLE
Check docs coverage for dvc 2.8

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2973]
This is a tracking issue to check whether the following new features and bug fixes (should) have corresponding docs updates/PRs. 

## 🚀 New Features and Enhancements 

- [x] Fix exp show --sort-by issue iterative/dvc#6675 (iterative/dvc#6764) @eggqq007
- [x] webhdfs: migrate to fsspec (iterative/dvc#6662) @isidentical
- [x] hdfs: migrate to fsspec (iterative/dvc#6604) @isidentical
- [x] command: Should not consume 'print' to output default remote info (iterative/dvc#6650) @eggqq007
- [x] command: output prettify json in tty (iterative/dvc#6743) @eggqq007
- [x] Run on Python3.10 (iterative/dvc#6745) @skshetry (#2975)
- [x] http: explicitly retry all http-related errors (iterative/dvc#6728) @isidentical
- [x] exp init: introduce `--with={default,live}` flag (iterative/dvc#6716) @skshetry (#2974)
- [x] cli: add short alias for --show-{csv,json,md} (iterative/dvc#6711) @skshetry
- [x] command: Show dvc list output in pretty JSON format (iterative/dvc#6647) @eggqq007
- [x] exp init: show heading based on the presence of dvc.yaml file (iterative/dvc#6701) @skshetry
- [x] exp init: support interactive and explicit options (iterative/dvc#6681) @skshetry
- [x] better exception messages for schema errors (iterative/dvc#6679) @skshetry
- [x] ui: support pager universally (iterative/dvc#6692) @skshetry
- [x] add alias ls for dvc list (iterative/dvc#6683) @ap-kulkarni
- [x] remote: add support for Amazon S3 timeout configuration (iterative/dvc#6634) @whysage
- [x] merge yaml parsing and schema validation into one, aka strictyaml.load (iterative/dvc#6661) @skshetry
- [x] exceptional exceptions (iterative/dvc#6654) @skshetry
- [x] Allow user to specify different state and index tmp dir locations (iterative/dvc#6419) @nueschs

## 🐛 Bug Fixes 

- [x] Fix exp show --sort-by issue iterative/dvc#6675 (iterative/dvc#6764) @eggqq007
- [x] gs: use 3-char prefixes (iterative/dvc#6759) @isidentical
- [x] Fix dvclive running subdir (iterative/dvc#6740) @daavoo
- [x] build(setup): avoid leaking tests package into site-packages (iterative/dvc#6585) @pwoolvett
- [x] doctor: fixes unknown cache directory error on some windows mapped network shares (iterative/dvc#6364) @anasitomtn
- [x] http: allow reading proxies from the current environment (iterative/dvc#6688) @isidentical
- [x] ssh: fix path normalization on windows (iterative/dvc#6517) @isidentical
- [x] ssh: bundle bcrypt by default (iterative/dvc#6678) @isidentical
- [x] fix dvc[all] (iterative/dvc#6657) @casperdcl
- [x] progress: do not block on async filesystems (iterative/dvc#6612) @isidentical
