### ISSUE TITLE
ref: replace `dvc run` examples with `dvc stage add` + `dvc exp run` or `dvc repro`

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2997]
In the command reference, there are several examples using `dvc run`. Replacing these with `dvc stage add` may lead to clear examples. 

- [x] #3023
- [x] #3031
- [x] #3183
- [x] #3070
- [x] ref: Update index page
- [ ] ref: Update `dvc run` references in `dvc gc`
- [x] ref: Update `dvc run` references in `dvc import-url`
- [x] ref: Update `dvc run` references in `dvc init`
- [x] ref: Update `dvc run` references in `dvc metrics`
- [x] ref: Update `dvc run` references in `dvc params`
- [x] ref: Update `dvc run` references in `dvc plots`
- [x] ref: Update `dvc run` references in `dvc repro`
- [x] #3103
- [x] #3053
- [x] ref: Update `dvc run` references in `dvc status`
- ref: Add a "deprecated" notice to `dvc run` ?

**Comment by jorgeorpinel** [comment]
>  ref: Add a "deprecated" notice to dvc run

I don't think it's deprecated though. I forget what the plan is but I think there's an issue about it on the core repo. Cc @dberenbaum

**Comment by iesahin** [comment]
I believe, from the earlier discussions, `dvc run` is deprecated and may be removed in later versions. Can we have an official decision on this? @shcheklein @dberenbaum

**Comment by dberenbaum** [comment]
Related discussions/issues:

* https://github.com/iterative/dvc.org/issues/2076
* https://github.com/iterative/dvc/issues/5846
* https://github.com/iterative/dvc/discussions/5819

We haven't made progress towards deprecation, but I think we have at least agreed on emphasizing `stage add`. I have no objection to replacing the examples.

**Comment by jorgeorpinel** [comment]
Could the DVC team finish the cmd ref updates related to this @dberenbaum ?

@iesahin maybe we should just double check no other docs still use `run` unnecessrily.

**Comment by jorgeorpinel** [comment]
Looks like a few tasks may still be pending or need discussing a little. Reopening for now... I'll update the check boxes in the description if needed.

**Comment by jorgeorpinel** [comment]
UPDATE: Looks like it's just about https://dvc.org/doc/command-reference/gc but as long as we haven't actually deprecated `run` we can leave that link (as well as the one in https://dvc.org/doc/command-reference/status). So never mind 😬

**Comment by jorgeorpinel** [comment]
Do we have an issue to do the same for guides and use cases though? ⌛

**Comment by dberenbaum** [comment]
@jorgeorpinel I'm not sure about guides and use cases, but I did take a look at getting started, and it seems like it will require more of an overhaul than just replacing text. I think it would have to be a dedicated project for someone to update it.

**Comment by jorgeorpinel** [comment]
> I did take a look at getting started, and it seems like it will require more of an overhaul than just replacing text

Yeah let's leave that to @iesahin for now then?

BTW I did find an existing issue that's related so I'm updating it to follow up on all this: https://github.com/iterative/dvc.org/issues/2076

**Comment by iesahin** [comment]
I took over #2076. We can discuss the remaining parts there. This issue was specific to REF.
