### ISSUE TITLE
check documentation for dvc 2.9 release

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#3074]
## 💣 Breaking Changes 

- [x] exp diff: Remove `--old` option. (iterative/dvc#6888) 

## 🚀 New Features and Enhancements 

- [x] introduces `exp init` command 
- [x] render: image: make html less ugly (iterative/dvc#7075) 
- [x] plots: collect: provide callable for data resolution (iterative/dvc#6832) 
- [x] live: Call webbrowser.open (iterative/dvc#6913) 
- [x] scm: hint to autostage (iterative/dvc#6985) 
- [x] exp show: Add `--only-changed` option (iterative/dvc#6867) 

## 🐛 Bug Fixes 

- [x] exp: respect repo `hardlink_lock` config for the exp scm lock (iterative/dvc#7030) -young
- [x] dulwich: fallback to default SSH keys in asyncssh vendor (iterative/dvc#6983) 
- [x] plots: special chars handling for vega plots paths (iterative/dvc#6900) 
- [x] params: Use `ast.literal_eval` for python params. (iterative/dvc#6954) 
- [x] push: fix http storage ignoring method setting (iterative/dvc#6981) 
- [ ] hardlink: fallback to other link methods if "Function not implemented" is raised (iterative/dvc#6963) 
- [x] argparse: dont override cmd (iterative/dvc#6958) 

## 🔨 Maintenance 

- [x] build(deps): Bump scmrepo from 0.0.1 to 0.0.2 (iterative/dvc#7055) 
- [x] packages: build binary pkgs with Python 3.9 (iterative/dvc#7016) 
- [x] dvc.scm: refactor exceptions (iterative/dvc#7017) 
- [x] build(deps): Bump adlfs from 2021.9.1 to 2021.10.0 (iterative/dvc#6734) 
- [x] build: bump sshfs from 2021.8.1 to 2021.11.2 (iterative/dvc#6999) 
- [x] build: bump pyinstaller from 4.6 to 4.7 (iterative/dvc#6960) 
- [x] dvc: get rid of path_info (iterative/dvc#6946)

**Comment by jorgeorpinel** [comment]
Thanks @iesahin . Usually only new features may need matching docs updates.

**Comment by jorgeorpinel** [comment]
p.s. are you taking this one? (I did the last one 😬)

**Comment by iesahin** [comment]
I can take this one, no problem, I also did [the last one](https://github.com/iterative/dvc.org/issues/2973) in a similar fashion. :)) I remember because everyone involved was notified :))

**Comment by jorgeorpinel** [comment]
Thanks! 

> p.s. by "last one" I meant [2.8.3](https://github.com/iterative/dvc/releases/tag/2.8.3). I usually check them without creating an issue here but create specific ones instead e.g. https://github.com/iterative/dvc.org/pull/3065

**Comment by iesahin** [comment]
Bugfix releases usually don't (and shouldn't) contain any documentation changes. Anyway, thank you. I can do this.

**Comment by iesahin** [comment]
I've read all of the PRs in the release. Great work @iterative/dvc  Thank you 👏🏼 🎊

**Comment by jorgeorpinel** [comment]
Nice
