### ISSUE TITLE
DVC home page + updates

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#3833]
UPDATE: Jump to https://github.com/iterative/dvc.org/issues/3833#issuecomment-1262904131.

- Q: Are there any issues with the download button pending?
- [ ] Update animated `dvc` command samples (compare to README's [Quick start](https://github.com/iterative/dvc#quick-start)).
- [ ] “Learn more”: do we still want this Header, diagrams and sections? Update it at least -- should we unify this with Features/ Use Cases?
- [x] **Features** page: Remove it? (check analytics) And/or merge with [Core features](https://dvc.org/doc/user-guide/overview#core-features) from docs
- [ ] [**Use Cases**](https://dvc.org/doc/use-cases): Should probably go top-level (not in /doc); Replace **Features** page? Extract (some) to iterative.ai ?
- (Advanced) Consider using more media types like videos or gifs.

**Comment by jorgeorpinel** [comment]
Cc @dberenbaum @shcheklein @iterative/websites any other needs?

From several of the above I can generalize that we have an unclear mix of features and use cases in different places. Should it be about value-proposition and competitive advantages in the home page (README framework), adoption in secondary landing pages ("applications"), and leave actual features for the docs?

From there we should make some decisions and start scheduling content and design work.

**Comment by dberenbaum** [comment]
I'm not sure where features should live, but otherwise LGTM.

**Comment by jorgeorpinel** [comment]
The OP seems reasonable, but as per a previous meeting, we should attempt to define what the DVC home page should be from scratch without considering existing content. After that we can see what existing content is still relevant and whether the original plan above still makes sense.

> @dberenbaum and @jendefig have been tasked to define and drive this one in the near future. Please include me (or others) in the parts where you think we can help (e.g. clarifying or combining Features vs Use Cases). Thanks

**Comment by dberenbaum** [comment]
Some thoughts on content:

* Features: for now, we can focus on 3 main components of DVC: data management, pipelines, and experiments.
* What it is: CLI tool with accompanying Python API and VS Code extension.
* Primary use case: reproducible ML model development.
* Other key info: open source, built to work with Git and typical software stack, focus on data-centric ML.

@shcheklein @jendefig Any thoughts?

**Comment by shcheklein** [comment]
> focus on data-centric ML.

Not sure about this one, but otherwise it seems like a reasonable start to me.

**Comment by dberenbaum** [comment]
One more thought: how much should it focus on the rest of the Iterative ecosystem (both Studio and other products)?

I'd suggest we mention the Iterative ecosystem and link to other tools without explanation, but explain that Studio is a commercial (but free for individuals) collaboration platform for DVC and the Iterative ecosystem.

**Comment by jorgeorpinel** [comment]
> Features: data management, pipelines, and experiments

"Features" may not be high-level enough. Should we focus on solutions/ use cases (value) for the home page? At least nearest to the top. Could be as easy as rephrase the "feature" names (and the way we present them) e.g. data mgmt -> manage data effectively; pipelines -> adopt GitOps for your ML workflows; etc. (just quick ideas)

**Comment by jendefig** [comment]
>Update animated dvc command samples (compare to README's [Quick start](https://github.com/iterative/dvc#quick-start)).
Shouldn't we look at the most used commands/workflows for this?

> “Learn more”: do we still want this Header, diagrams and sections?
The images for this section are very hard to understand unless you already know what DVC is and how it all works.  It's unclear what the icons are in the first image.  Even though I've looked at these images 100 + times, I did not realize until today the dotted lines that are showing the way through it.  They are far too light.  I think spending the time to turn this into an animated image would be desirable and make things significantly more clear. 

>should we unify this with Features/ Use Cases?
Yes.  I didn't understand why it was not on the landing page to begin with. (Other than it makes it long). And it is high up in the list, but for some reason has had an increasing bounce rate since late June, which must be because we added the link to the VS Code extension then right at the top.  I would suggest moving Features to the main landing page.
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/34289199/194950293-693546aa-128e-4b25-885f-b303b05c9a0c.png">

>[Use Cases](https://dvc.org/doc/use-cases): Should probably go top-level (not in /doc); Replace Features page? Extract (some) to iterative.ai ?
(Advanced) Consider using more media types like videos or gifs.

I think it would make sense to have these use cases as clickable blocks (building blocks) in some kind of diagram that harkens back to the Readiness scale that Jervis created.  Or clickable sections of the MLOps double infinity loop or Casper's diagram (which I can't find, but I know is somewhere in slack.).  This will orient people to where they are in the process conceptually.

**Comment by jorgeorpinel** [comment]
> look at the most used commands/workflows

We should project our intended default onboarding experience instead I think. Is that `exp init`? On CLI or on the VSCode extension? Maybe also add tabs for secondary onboarding using more traditional (and widely used) commands (`add, push, stage add, repro`). These are the most important product questions to answer first IMO.

> images for this section are very hard to understand unless you already know what DVC is

➕ 

> this into an animated image

Not sure. Maybe just much more simple diagrams you can read instantly.

> moving Features to the main landing page

[Features are kind of low level IMO.](https://github.com/iterative/dvc.org/issues/3833#issuecomment-1273463900) Depending what we mean by that word

> have these use cases as clickable blocks...

Good ideas but our current "use cases" are more of independent solutions, not really blocks to combine. Some can be combined but they're not meant to be like that, they're meant to capture people looking for solutions to certain high-level problems faced in the industry.

**Comment by jendefig** [comment]
@yathomasi We are ready to start exploring the design of the logo carousel for the DVC Home page redo.  The folder with logos is [here](https://drive.google.com/drive/folders/16d-HpXBBg8oYhQqTxU44EgdlZ_jlf1d3?usp=sharing).  We are still working on collecting them.  I would like to see it be a relatively thin line between sections, one logo high, so that it doesn't take up too much space and people can continue to digest the rest of the material on the site.  Also, this way it would look like it's never-ending.  Is it right to have this here or should we create a separate PR?

**Comment by dberenbaum** [comment]
Let's close this one and open new issues as needed for specific improvements.
