### ISSUE TITLE
update docs with cloud versioning info

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4089]
### Report

Docs to be updated:

- [ ] https://dvc.org/doc/start/data-management/data-versioning
~- [ ] https://dvc.org/doc/use-cases/data-registry/tutorial~
- [x] https://dvc.org/doc/user-guide/data-management (see [this PR](https://github.com/iterative/dvc.org/pull/4053/files#diff-6376fe6f727a73891706d35b9d7c0a0fc6dfe05c51adef6f75708f36f35df73e); may need a new page)
- [x] https://dvc.org/doc/user-guide/project-structure/dvc-files (add `version_id` and `push` fields)
~- [ ] https://dvc.org/doc/command-reference/config~
- [x] https://dvc.org/doc/command-reference/push
- [x] https://dvc.org/doc/command-reference/remote/modify
- [x] https://dvc.org/doc/command-reference/import-url
- [ ] https://dvc.org/doc/user-guide/data-management/cloud-versioning: add warning about automatic expiry and limited versions, especially for GCS since their defaults are very strict (cc @daavoo)
- [ ] reorder `dvc push` to be before git commit throughout the docs

**Comment by jorgeorpinel** [comment]
Do we have a timeline for this feature release? Expected DVC version? Thanks

**Comment by dberenbaum** [comment]
We are aiming for release around the start of December. I don't have an expected DVC version. The changes aren't breaking for now since users have to configure flags to use cloud versioning, so I don't think the version number matters too much. The plan is to put something out soon and start getting feedback rather than wait for a major release.

**Comment by dberenbaum** [comment]
@pmrowla Should we add `version_id` to https://dvc.org/doc/user-guide/project-structure/dvc-files?

**Comment by dberenbaum** [comment]
I think we can close this one after we address that (we can address adding more high-level content into use cases, get started, etc. in separate issues).

**Comment by jorgeorpinel** [comment]
Also the `config` and `push` refs?

**Comment by dberenbaum** [comment]
> Also the `config` and `push` refs?

For `config`, the `remote` section just refers users to the `dvc remote` ref, so I don't think there's actually an updated needed.

For `push`, I'm not sure what needs to be added. Maybe an example?

**Comment by dberenbaum** [comment]
Actually, the https://dvc.org/doc/command-reference/import-url synopsis is missing the `--version-aware` option, so that also needs to be done.

**Comment by dberenbaum** [comment]
> * especially for GCS since their defaults are very strict (cc @daavoo)

@daavoo Do you remember where you saw this?

**Comment by daavoo** [comment]
> @daavoo Do you remember where you saw this?

In the GCS page when you create a new bucket with versioning enabled

**Comment by shcheklein** [comment]
@dberenbaum do we plan to do any other updates within this epic?

**Comment by dberenbaum** [comment]
I hope to at least make some progress on the other checkboxes so we can close this one.
