### ISSUE TITLE
3.0 checklist

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#4513]
```[tasklist]
### Experiments updates
  - [x] \#4440
  - [x] \#4498
  - [x] \#4087
```

```[tasklist]
### Other updates
- [ ] #4423
- [ ] #4589 
- [ ] #4532
- [ ] #4585
```

```[tasklist]
### [Deprecations](https://github.com/iterative/dvc/issues/7093)
- [ ] #4574
- [x] https://github.com/iterative/dvc/pull/9271 (@daavoo can we revive #4442?)
- [x] Remove stage-level vars (@skshetry)
- [x] https://github.com/iterative/dvc/issues/4658 (@pmrowla)
- [x] #4594 (rename `dvc add --jobs` to `dvc add --remote-jobs`; remove `dvc add --file --recursive --desc --type --labels --meta`)
- [ ] #4441
- [x] https://github.com/iterative/dvc.org/pull/4415
- [x] Remove `exp show --html`
- [ ] https://github.com/iterative/dvc.org/pull/4443
- [x] Remove `dvc run` (@skshetry)
- [x] Remove `--show-json`/`--show-csv`/`--show-md` in favor of existing `--json`/`--csv`/`--md` flags.
- [x] Docs for https://github.com/iterative/dvc/issues/9457 (@daavoo)
```

```[tasklist]
### Nice to have
  - [ ] \#4401
```

**Comment by skshetry** [comment]
> `dvc stage add --run` (@skshetry)

`stage add --run` is  not 3.0 only feature. It was documented in https://github.com/iterative/dvc.org/pull/4558.

**Comment by skshetry** [comment]
`dvc run` is already removed, thanks to @daavoo in https://github.com/iterative/dvc.org/pull/4296.

**Comment by dberenbaum** [comment]
Working on experiments guide updates separately, but I think we can close this.
