### ISSUE TITLE
Stabilizing `import-db`

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#5087]
### Report

For now, we are considering `import-db` to be an experimental command. See #5033.

When stabilizing:

```[tasklist]
### Tasks
- [ ] Remove admonition warning
- [ ] Add docs for `db` schema in `.dvc` file
- [ ] Mention `import-db` in `dvc update`
```

**Comment by skshetry** [comment]
@dberenbaum, should we remove the warning and consider it stable?
