### ISSUE TITLE
guide: consolidate external data mgmt guides

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#520]
done
- ~~External dependencies and outputs.~~

next
- [ ] Add proper links through out other doc sections.
- [ ] Explain external cache here or in the cache docs but not in the shared dev server use case, because shared cache isn't compatible with external data (see https://github.com/iterative/dvc/issues/4520#issuecomment-774649551)
- [ ] Clarify about cache link types per remote location as discussed in #764.
- [ ] Decide whether how-to is also needed per https://github.com/iterative/dvc.org/issues/563#issuecomment-521731979

later?
- [ ] Move them under single **Manage External Data** section (rel #144) with some motivation in the index. [or rewrite completely?]
- [ ] Clarify differences and use cases for external storage mechanisms (see #566) [terminology]
- [ ] Add info about NFS (see #103) [remote-related]
- [ ] Probably also address #774 about encrypted buckets

**Comment by dashohoxha** [comment]
I am working on this.
Related issues: #499, #143, #566 
The structure of the pages would be like this:

- External Data and Cache
  - Local Files and Directories
  - SSH
  - Amazon S3
  - Google Cloud Storage
  - HDFS
  - HTTP

It will consolidate (and deprecate):
- [External Dependencies](https://dvc.org/doc/user-guide/external-dependencies)
- [Managing External Data](https://dvc.org/doc/user-guide/managing-external-data)

The consolidated pages may also include configuration options for different remote types, from this page: https://dvc.org/doc/command-reference/remote/modify

**Comment by shcheklein** [comment]
I think this structure looks too complicated and is not correct. Most important here is to explain when and why the external data management is needed. Then there should be two sections - dependencies and outputs (and we should think about this name) - those are two very different concepts. Then example for specific clouds - can be a page or section with multiple pages.

**Comment by dashohoxha** [comment]
> I think this structure looks too complicated and is not correct.

I agree. After thinking a bit about it, it seems that that structure might be suitable for a page/section about "Remote Storage Types", like this:

- Remote Storage Types
  - Local Files and Directories
  - SSH
  - Amazon S3
  - Google Cloud Storage
  - HDFS
  - HTTP

> Most important here is to explain when and why the external data management is needed.

Exactly. For example I am not sure when a remote cache might be useful. I can think of two cases:
1. When the remote cache is actually a local directory.
2. When the project is used just for dataset management (there are no stages).

Have I missed any other cases when it might be a preferred choice? The case that is used currently as an example (copying datafiles to a remote storage) does not seem convincing.

**Comment by shcheklein** [comment]
I think that Remote Storage Types by itself can and should be part of the "Data Sharing" section you made.

>  For example I am not sure when a remote cache might be useful.

In general you need all "external stuff" when you have some processing system that writes/read directly into/from it. E.g Spark that runs on top of S3 and crunches data that is too large to bring it to local machine. It means some mixed cases - e.g. raw data is large and you read it directly from S3 but intermediate artifacts, models, etc are stored locally.

So, rule of thumb - think about script in any language. If it internally has a pointer to S3, or any other cloud/remote storage (relative to the location you run this script from) it means you need some external data management.

**Comment by dashohoxha** [comment]
> I think that Remote Storage Types by itself can and should be part of the "Data Sharing" section you made.

I am planning to make a separate section for the Remote Storage Types. After that we can see whether it makes sense to include this section under the "Data Sharing" section. But I think that it is going to have many details and will not be suitable to be a subsection of "Data Sharing".

**Comment by dashohoxha** [comment]
I have a question.

If you check the new section [External Data and Remotes](https://dvc-org-pr-807.herokuapp.com/doc/user-guide/external-data), you will notice that some remote types (SSH, Amazon S3, GS, HDFS) have subsections about external dependencies and outputs, while the others (S3 API, Azure, Aliyun OSS) do not have such subsections.

This is simply because their information is missing from the pages that are being consolidated:
- https://dvc.org/doc/user-guide/external-dependencies
- https://dvc.org/doc/user-guide/managing-external-data

I suspect that external dependencies and outputs work the same way for these remote types as well. However I cannot test this for each remote type (I am just reorganizing and rewriting the information that is already available on these pages and on the man pages of `dvc remote`).

Can someone confirm that the external dependencies and outputs work the same way for all the remote types (in particular for S3 API, Azure and Aliyun OSS)?

**Comment by shcheklein** [comment]
@efiop has more up to date info on this in terms of specific remotes supporting specific features.  But in general, that information is not present because on certain types of remotes we do not support external deps/outs yet. May be even some table would be beneficial with a summary of features supported by different remotes.

`S3 API` name is a bit confusing btw. It should be something like - S3 Compatible or may be there is a specific term for that.

**Comment by jorgeorpinel** [comment]
Added a checkbox about the external cache section (per https://github.com/iterative/dvc.org/issues/654#issuecomment-775489955)

**Comment by rmlopes** [comment]
Hi,
I would like to setup an external Azure remote for the run-cache. It is not mentioned  in the docs how to configure it (similarly to what is done with S3 or GCloud). Reading though this issue it looks like it is not supported yet, am I right?

**Comment by shcheklein** [comment]
@rmlopes could you please move it to a separate question please in the DVC or DVC.org repo?

**Comment by rmlopes** [comment]
Thanks @shcheklein, Opened a new issue at DVC.org #2429

**Comment by jorgeorpinel** [comment]
Hi. What parts of this epic are still high priority given that `--external` is now considered an experimental feature that needs redesigning?

**Comment by jorgeorpinel** [comment]
p.s. I reordered the checkboxes, please org as needed.

**Comment by casperdcl** [comment]
I think the most important thing is to clarify the feature's use case(s), and specifically how rare said use case(s) is/are (i.e. *If you're reading this, you probably shouldn't*).

There is so much confusion on this point that even we often don't get it (vis. https://github.com/iterative/cml/issues/561#issuecomment-854944483). Things we need to document:


- there are 3 different uses of a DVC remote
    i. data VCS remote (analogous to Git remote)
    ii. data artefact host (analogous to Dropbox shareable links)
    iii. DVC cache (**useless by itself. no it doesn't solve ur end-user use-case, soz.**)
- (i) is by far the most common
- (ii) is rare
- (iii) is a necessary requirement to do (ii) and does not serve any other purpose.
    - Do you want to avoid having a local cache for your local outputs, instead storing the cache remotely? In which case you seem to be talking about the equivalent of a shallow clone, which is by default what `dvc pull/checkout` does
    - Do you want to [mirror your local cache remotely](https://github.com/iterative/cml/issues/561#issuecomment-854944483)? In which case you seem to be talking about the equivalent of uploading your `.git` folder somewhere. Don't do this - just `git/dvc push` to a remote instead (i).

**Comment by shcheklein** [comment]
> i.e. "If you're reading this, you probably shouldn't"

It's already mentioned for the external data management (ext dependencies are simpler and can be used completely separately), right? 

To clarify, I think those two existing sections in the UG do not cover in any way anything from the list @casperdcl mentioned. Also, this ticket is primarily about "external data management". Managing remotes in a regular DVC way is not considered part of it. All the things you mention @casperdcl they are not part of this ticket to my mind, if I understand them correctly. There should something like a regular "Data Management" section that explains it.

Description for this ticket is a bit messy at the moment to be honest. The whole initial idea was to consolidate properly use cases around large data that you don't want to bring locally and/or into DVC remote at all. May be include/may be not share cache scenario, or at least mention this as an alternative.

**Comment by casperdcl** [comment]
Not quite sure I follow @shcheklein - do you mean I should raise a separate issue?

**Comment by shcheklein** [comment]
@casperdcl most likely yes, but I'm not 100% sure on this. I'm not 100% sure about your specific concerns - e.g. are they indeed about the what-we-call external outs/deps (and external cache - please don't mix it with a `dvc cache dir` scenario), or about managing shared cache and regular remotes.

**Comment by dberenbaum** [comment]
Not sure where is best to add this, but we continue to see confusion about how to use DVC with externally stored data, especially when working in cloud-based environments like Databricks, Sagemaker, and Colab. See the discussions below:

* https://github.com/iterative/dvc/issues/4336#issuecomment-1472283792
* https://discord.com/channels/485586884165107732/563406153334128681/1088652943584153673
* https://discord.com/channels/485586884165107732/1089910570888724520/1089933356269047869

**Comment by dberenbaum** [comment]
Another report of this confusion: https://discord.com/channels/485586884165107732/485596304961962003/1095518763228610570.

Making this p1. I will try to reword/reorganize the info here.
