### ISSUE TITLE
use-cases: revise so they're more high level "landing pages"

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#820]
Use cases should have a different focus, so they are more high level and serve as landing pages – single web page that appears in response to clicking on a search engine optimized search result – leaving most details to the user guide. Some relevant quotes from https://github.com/iterative/dvc.org/pull/784#issuecomment-558403171:

> This section should answer the question of an infrastructure, DevOps, MLOps folks on how DVC can help them. How can it be used, in what high level scenarios. (And it's even okay if they overlap in this case.)

> To reiterate on the Use Cases vs User Guide:
**Users Guide** is like a car owner's manual - a lot of details, how tos, etc.
**Use Cases** would be like explaining how that car can be used (potentially referring a lot to the owner's manual to cover the technical details) - driving from home to work, renting, taxi, etc

~~Note: perhaps we could split this issue into 3. Not 4 because Data Registry is already written in this direction in #818.~~

Ideas:

- [ ] IN PROGRESS #654 extract details from use cases and possibly other redundant docs (e.g. some tutorials) into ~~blog posts~~ user guide? - #2482

---

Extracted to #2490:

- [x] #1722 write use cases correctly and extract how-to/tutorials into separate pages
- [ ] IN PROGRESS? #862 new case: **DVC in Production** (probably touch MLOps topics) - #2404
- [x] #857 Special content previews for SEO
- [x] #986 small **shared dev server** case update
- [ ] #194 About ML on a remote machine
- [ ] #2431 About specific ways to deploy ML models
- [ ] #2270 About Experiment Management
- ~~QUESTIONED #682 new case about data **partitioning and compression** ?~~
   > Use cases should have a different focus, so they are more high level and serve as landing pages – single web page that appears in response to clicking on a search engine optimized search result – leaving most details to the user guide.

**Comment by jorgeorpinel** [comment]
Priority @shcheklein? 🙂

**Comment by shcheklein** [comment]
I think p2 for now. Too many things in play already.

**Comment by jorgeorpinel** [comment]
Summary on MLOps-related use case ideas:

- **Training on a remote machine** #194 was the first idea and would narrowly focus on remote SSH executors. We can prob consider it part 3.0 experiments now, I think? (I can't find the related issue or discussion but I know there's one).
- **DVC in Production** #862 sounds broad but it intends to define and doc best practices around "synchronizing" DVC pipelines between experimental local dev and changing prod envs (I think). Cc @dmpetrov 
- **CI/CD for ML** (PR) #2404 is a bit broad so far but in the process of being narrowed down. Not clear what it will cover exactly but it'll likely include at least continuous integration using DVC + CML mentions. Cc @casperdcl 
- **Deploying models for real-time inference** #2431 may be a bit narrow but adds interesting edge to the model deployment topic, specifically model registries and real-time data streaming. Cc @dberenbaum 
- **Model zoo** (see https://github.com/iterative/dvc/issues/2719#issuecomment-555373498) Whether using a DVC repo to centralize ML model management is fundamentally different from general [data registries](https://dvc.org/doc/use-cases/data-registries) (possibly our most popular UC) has been a recurrent question. I think that probably yes but not sure how exactly.

**Comment by shcheklein** [comment]
Should this be a separate story ticket (new use cases vs revising existing ones)?

**Comment by jorgeorpinel** [comment]
OK: #2490
